volumes:
  hoge:

services:
  next:
    build:
      context: .
      dockerfile: docker/next/Dockerfile
    container_name: next-hoge
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - hoge:/app/node_modules
    command: npm run dev